### ISSUE TITLE
Add video support for spotlight images.

### ISSUE THREAD

**Issue by jaredhanson11** [jaredhanson11/tjef-redesign#6]
Add to `spotlight.handlebars` template ability to accept a video instead of img and then add iframe with youtube video linked instead of img.

**Comment by jhanreg11** [comment]
Data for video slide:
- Video URL: "https://www.youtube.com/watch?v=ar-H-pzRZ1k&feature=youtu.be"
- Description: "The Westfield Center seeks to promote dialogue among keyboard performers, scholars, and instrument makers. One aspect of this mission is the Concert Scholar Program, designed to give talented young keyboard players in the early stages of their performing career an opportunity to perform on excellent instruments located throughout the country.

This program, made possible through the support of The John Ernest Foundation, provides a three concert tour during the academic year following receipt of the award. The award is based on the concept of "student mentoring" and experiential learning, and as such, is intended to develop the student's skills as a performer, as well as his or her ability to meet and successfully interact with people in a professional and social context. Concerts are sponsored by TJEF which provides travel, and by the hosting institution, which provides hospitality. While there is no monetary award, the concert scholar receives a free membership to the Westfield Center.

The John Ernest Foundation first connected with Kristian Bezuidenhout when he won the Westfield Concert Scholar award. TJEF salutes his success. Mr. Bezuidenhout began his education in Australia and completed his studies at the Eastman School of Music. He has since become a maestro of the fortepiano,
harpsichord, and piano. Mr. Bezuidenhout received international acclaim at 21 after winning the celebrated first prize and audience prize at the Bruges Fortepiano Competition in Belgium. In 2013 he was nominated by Gramophone Magazine for Artist of the Year. Kristian has also demonstrated his musical prowess with some of the world’s leading ensembles such as the Orchestra of the Age of Enlightenment, Freiburger Barockorchester, the Chicago Symphony Orchestra along with guest-directing the English Concert. Kristian now lives in London, but his recitals take him across the world, from the United States to Japan."

**Comment by jaredhanson11** [comment]
Fixed by #10
